version: '3.8'

services:
  menu-opciones-app:
    build: .
    container_name: menu-opciones-app
    ports:
      - "3004:3000"
  
  nginx:
    image: nginx:latest
    container_name: nginx-menu-opciones
    ports:
      - "8084:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - menu-opciones-app
